name: Mozzart Scraper

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: |
          pip install playwright
          playwright install chromium
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run
        run: |
          xvfb-run python mozzart_human.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: debug.txt
